# Generated by Django 5.0.3 on 2024-03-21 16:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="YTVideo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("video_url", models.URLField(verbose_name="Video URL")),
                ("published_at", models.DateTimeField(verbose_name="Published At")),
                (
                    "channel_title",
                    models.CharField(max_length=100, verbose_name="Channel Title"),
                ),
                ("thumbnail_url", models.URLField(verbose_name="Thumbnail URL")),
                (
                    "upload_status",
                    models.CharField(
                        choices=[
                            ("deleted", "deleted"),
                            ("failed", "failed"),
                            ("processed", "processed"),
                            ("rejected", "rejected"),
                            ("uploaded", "uploaded"),
                        ],
                        default="uploaded",
                        max_length=10,
                        verbose_name="Upload Status",
                    ),
                ),
                (
                    "privacy_status",
                    models.CharField(
                        choices=[
                            ("private", "private"),
                            ("public", "public"),
                            ("unlisted", "unlisted"),
                        ],
                        default="public",
                        max_length=10,
                        verbose_name="Privacy Status",
                    ),
                ),
                ("like_count", models.IntegerField(verbose_name="Like Count")),
                ("dislike_count", models.IntegerField(verbose_name="Dislike Count")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "YouTube Video",
                "verbose_name_plural": "YouTube Videos",
                "db_table": "yt_video",
                "ordering": ["-published_at"],
            },
        ),
    ]
