# Generated by Django 5.0.3 on 2024-03-21 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ytvideo",
            name="dislike_count",
        ),
        migrations.RemoveField(
            model_name="ytvideo",
            name="like_count",
        ),
        migrations.RemoveField(
            model_name="ytvideo",
            name="privacy_status",
        ),
        migrations.RemoveField(
            model_name="ytvideo",
            name="upload_status",
        ),
    ]
