# Generated by Django 5.0.3 on 2024-03-21 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_ytvideo_dislike_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ytvideo",
            name="next_page_token",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Next Page Token"
            ),
        ),
    ]
